### PR TITLE
Add  blog post detailing example of regridding to POP grid

### PR DESCRIPTION
**Pull request by mgrover1**

### CODE REVIEW

**Review by mnlevy1981 — CHANGES_REQUESTED** [review]
The file is too large to use the in-line comments, but I'll try to list these suggestions in the order they appear in the document

> For this example, we will download a file from the World Ocean Atlas, which includes a variety of variables such as temperature or salinity from the World Ocean Database.

This reads as through the file will contain multiple variables. Since you already mention

> Only a few variables are available at 0.25 degree resolution, so in this example, we will look at Temperature since that is a field that is in our output and we are using high resolution (0.1 degree) output.

and give a decent overview about WOA (mentioning they have many variables and a few resolutions), the first sentence isn't the right way to start this section.

****

> One could also use an example from the Pangeo-Forge documentation accomplish this data-access task, since there is a "recipe" for using data from the World Ocean Atlas.

You're missing the word "to" between "documentation" and "accomplish"

****

> The calendar units have units months since months since 1955-01-01 00:00:00,

Lots of repeating text here...

****

> `model_ds = dsets['ocn.pop.h.g.e22.G1850ECO_JRA_HR.TL319_t13.004']`

I see that you are using our high-res BGC run for this notebook. Since you're looking at temperature, it might make more sense to look at one of Alper's runs since he has finished a full JRA cycle. You should reach out to see if time series has been generated (and, if so, where it is), but history files are in `/glade/campaign/cgd/oce/altuntas/g.e20.G.TL319_t13.control.001/ocn/hist` for years 1-25 and `/glade/campaign/cgd/oce/altuntas/g.e20.G.TL319_t13.control.001_hfreq/ocn/hist` for 26-61. With that run, year 1 corresponds to 1958 so (if I'm doing my math right) years 24 - 53 would span 1981-2010

****

> The naming syntax is: `woa_{pop_grid}_{regrid_method}.nc`

where did you get this convention from? The CESM convention seems to be `map_{srcgrid}_TO_{destgrid}.{maptype}.{date}.nc`, where `destgrid = tx0.1v3`, `maptype=aave` (shorthand for area-averaged, which is the type of conservative map used), and the date stamp is `YYMMDD`. I'm not sure what the best choice for `srcgrid` would be; probably `0.25x0.25` although that doesn't give any indication as to where the cell centers are (recall that the WOA and GLODAP 1 degree grids are offset by 0.5 deg in longitude, but I think CESM thinks of them both as `1x1`)

**Comment by mnlevy1981** [comment]
So a combination of minor nitpicks and a couple of bigger things to consider changing, but overall it looks great!

**Comment by mgrover1** [comment]
@mnlevy1981 - okay! I can reach out to Alper - if I make that bigger change, I might have to push back this post until mid next week to get permission from him to use it, generate a new intake catalog for that, and redo some of the computation... do you think it's okay to just use the sample data from the hires data? Or do you think it is worth holding off until next week?

**Comment by mnlevy1981** [comment]
> do you think it's okay to just use the sample data from the hires data? Or do you think it is worth holding off until next week?

my preference would be to wait until next week, but another option would be to publish now and then update the post with the better data once it's available. I know these posts are geared towards showing how to use the software, but I think the examples we give should still be as scientifically accurate as possible and in this case I think the completed JRA cycle is preferable to the one that is only halfway there.

**Comment by mgrover1** [comment]
@mnlevy1981 I made some more changes - can you take a look when you get a chance?

**Review by mnlevy1981 — CHANGES_REQUESTED** [review]
This looks really nice! One last small typo to clean up and a small suggestion, both from

> Generating these weights can be quite computationally expensive - to save time in the future, we can save the weights file. The naming syntax we use here (although not neccessarily the standard) is: `woa_{pop_grid}_{regrid_method}.nc` where are using the tenth degree (`tx0.1v3`) grid and a `conservative` regridding method

The typo is just a missing "we" in "where are" in the second sentence.

The small suggestion actually turned into a huge wall of text... I like the first clause of that sentence a lot more than the version it replaced, but I'm wondering if it's worth mentioning that there is a huge cache of mapping files available on glade already (`/glade/p/cesmdata/cseg/inputdata/cpl/cpl6` and `/glade/p/cesmdata/cseg/inputdata/cpl/gridmaps`) that are typically maps from one CESM component grid to another. In this notebook you're generating a weights file for one specific case and it might not be worth making the weights more widely available, and since you're just using this file as a one-off you want the name to be descriptive but it doesn't necessarily have to conform to any convention.

Alternatively, should think about storing these weight files alongside the observational datasets? If we had maps from the 1 deg -> `gx1v7`, 1 deg -> `tx0.1v3`, and 0.25 deg -> `tx0.1v3` available, could we just store the obs on native grid and provide the weight files / this blog post to help users get the data onto the model grid? In that case, I think we would want this notebook to show how we generated those weight files but you could hard-code a path to somewhere on `glade` or `campaign` when you write the file (and then we reopen the can of worms about how to name the file).

**Comment by mgrover1** [comment]
@mnlevy1981 what would you suggest replacing this section with? What would be the best way of covering all those points?

**Comment by mnlevy1981** [comment]
How does

> Generating these weights can be quite computationally expensive, so they are often saved to disk to prevent needing to recompute them in the future. The MCT-based coupler in CESM uses these weight files to map fields being passed from one component to another, so many weight files are available in `/glade/p/cesmdata/cseg/inputdata/cpl/cpl6` and `/glade/p/cesmdata/cseg/inputdata/cpl/gridmaps`. The naming syntax we use here is slightly different than the convention that has evolved in the CESM mapping files: `woa_{pop_grid}_{regrid_method}.nc`, where we are using the tenth degree (`tx0.1v3`) pop grid and a conservative regridding method.

Since you're using `wget` to download the file instead of pointing to an existing copy on disk (which is smart, since we haven't decided on a final location for ocean obs yet), it probably doesn't make sense to move the weight file out of the local directory.

Hmm... are you going to update this post once we have a home for this data in campaign or `/glade/p`?

**Comment by mgrover1** [comment]
I can update the this post once we have a home!

**Comment by mnlevy1981** [comment]
> I can update the this post once we have a home!

in that case, maybe it makes sense to update "where are" to "where we are" now and save the rest of the re-write for the update?

**Comment by mgrover1** [comment]
I think it's worth including the rewrite! I think it is more helpful than the previous version... We can update in the future, but letting people know there are some weights files on GLADE already is helpful

**Review by mnlevy1981 — APPROVED** [review]
All my concerns have been addressed in conversation and / or later commits, this looks ready to go to me.

**Comment by mgrover1** [comment]
@mnlevy1981 I had a small typo in the title - went ahead and changed that, and we should be good to go... waiting to double check the rendered version to make sure that all went through.

**Pull request merged**
