### PR TITLE
update dask dates post - attempt 2

### PR DESCRIPTION
**Pull request by jukent**
Trying a different workflow from #80 were it will be easier to address the linting error

### CODE REVIEW

**Comment by jukent** [comment]
Closed and re-oppened the PR because sometimes that helps when the readthedocs build fails due to memory consumption.

**Review by andersy005 — APPROVED** [review]
👍🏽

**Review by mgrover1 — APPROVED** [review]
Looks good

**Comment by jukent** [comment]
> Looks good

The build is still failing on memory. Should we merge this or try to fix that somehow?

**Comment by mgrover1** [comment]
> > Looks good
> 
> The build is still failing on memory. Should we merge this or try to fix that somehow?

I think we can merge this with rtd failing... We are building the site via github pages anyway, the rtd is more for viewing a preview of the site. I will need to request more storage on rtd in the future...

**Comment by andersy005** [comment]
@jukent, the missing file extension (`posts/dask-tutorial-update`) may result in some issues when building the HTML. In case this file doesn't show up on the built site, adding an extension (`posts/dask-tutorial-update.md`) should fix the issue

**Comment by jukent** [comment]
> @jukent, the missing file extension (`posts/dask-tutorial-update`) may result in some issues when building the HTML. In case this file doesn't show up on the built site, adding an extension (`posts/dask-tutorial-update.md`) should fix the issue

Good catch!

**Pull request merged**
