### PR TITLE
Create dask update post

### PR DESCRIPTION
**Pull request by jukent**

### CODE REVIEW

**Review by mgrover1 — COMMENTED** [review]
Looks good - could you take a look at the linting error?

**Comment by jukent** [comment]
> Looks good - could you take a look at the linting error?

The tests are failing on linting, but with error message `ModuleNotFoundError: No module named 'toml'` rather than pointing to a specific line with bad linting. This makes me believe the error could be outside of my one file? Any insight?

**Comment by mgrover1** [comment]
@andersy005 any idea what could be happening here? It appears that it is failing when running the linter... saying it doesn't have the `toml` package installed. Would we need to add this to `environment.yaml` file?

**Comment by andersy005** [comment]
> @andersy005 any idea what could be happening here? It appears that it is failing when running the linter... saying it doesn't have the `toml` package installed. Would we need to add this to `environment.yaml` file?


The pre-commit hooks need to be updated... These can be updated by running `pre-commit autoupdate` command

**Comment by jukent** [comment]
Thanks @andersy005 that seems to have worked! Over at #81

**Pull request closed without merging**
