### PR TITLE
update agenda

### PR DESCRIPTION
**Pull request by dcherian**
unfortunately i can't do this. have a sick kid this week.

Also, Brian V got in touch and let me know that they're planning a dask thing for early feb,

### CODE REVIEW

**Comment by katiedagon** [comment]
Can/should we replace it with an introduction to hack projects or discussion topics for Day 2? For that we might not need a full hour. 
I suggested something here: https://docs.google.com/document/d/1pcHLqvjkg7eT4wM6l9_GYgFef3gqOa-LL34m24ujBUY/edit
But someone else (@erogluorhan ?) will need to update the public agenda: https://docs.google.com/document/d/10cgElI2Rl8gCqH3oSQqEXzmW-3sSbrv9LQ9eM6A7v8g/edit?usp=sharing

**Comment by hCraker** [comment]
@katiedagon That's a great idea. Do we know who is leading the hackathon? I don't recall hearing about what the hack day projects are going to be

**Comment by katiedagon** [comment]
Let's discuss in the meeting this afternoon, I don't think this was determined yet.

**Comment by katiedagon** [comment]
@dcherian Can we include here all the updates to the agenda we discussed today?
Public version of the agenda: https://docs.google.com/document/d/10cgElI2Rl8gCqH3oSQqEXzmW-3sSbrv9LQ9eM6A7v8g/edit?usp=sharing

**Review by erogluorhan — APPROVED** [review]

**Pull request merged**
