### PR TITLE
Blog post for ESDS event recap

### PR DESCRIPTION
**Pull request by katiedagon**
This post has a summary of information and resources from the ESDS event a few weeks ago.

@erogluorhan Do you or Taysia have links to the recordings from the event? There is a placeholder to add those here.

@NCAR/esds-core, please feel free to review and add anything I missed that would be helpful to include.

### CODE REVIEW

**Review by dcherian — APPROVED** [review]
Thanks Katie, looks good to me! (aside from missing links)

**Comment by erogluorhan** [comment]
> > @erogluorhan Do you or Taysia have links to the recordings from the event? There is a placeholder to add those here.
> 
> Not yet; checking in with Taysia about this.

@katiedagon Taysia said she'd expect to wait for a few weeks for those recorded videos to be accessible and she'd follow up on them. We can either wait for that to merge this PR or get it merged without links.

**Comment by katiedagon** [comment]
@erogluorhan Thanks. Happy to wait for the recordings unless others prefer to post earlier.

**Comment by katiedagon** [comment]
@erogluorhan The links to the recordings are now updated in this blog post, I think we should be ready to post this.

**Review by hCraker — APPROVED** [review]
The links work as intended. Thanks for adding these so quickly!

**Pull request merged**
