### PR TITLE
Add graphviz intake example

### PR DESCRIPTION
**Pull request by mgrover1**
Example of visualizing what is in intake-esm catalog

### CODE REVIEW

**Comment by dcherian** [comment]
dang. very cool! I think you should make it a builtin function with intake-esm: `cat.visualize()`

**Comment by mgrover1** [comment]
> I think you should make it a builtin function with intake-esm: `cat.visualize()`
What would be the best way to setup this api? What would be the defaults?

**Comment by andersy005** [comment]
> I think you should make it a builtin function with intake-esm: cat.visualize()
> What would be the best way to setup this api? What would be the defaults?

I think this can be achieved via pandas' multi-index dataframe. I'm imagining a method that allows the user to provide a list of columns that we for constructing a multi-index dataframe from `col.df`. This multi-index dataframe can be turned into a nested dictionary that is then passed to `py-graphviz`. This is all speculation though:) An actual prototype/implementation would definitely be neat :)

**Review by andersy005 — APPROVED** [review]
This is so neat 👍

**Pull request merged**
