### PR TITLE
Correctly Calculating Yearly Average Post

### PR DESCRIPTION
**Pull request by mgrover1**
Based on conversations this week about the correct method, I put together a blog post walking through how to properly calculate yearly averages, with a comparison showing how things can go wrong.

### CODE REVIEW

**Comment by mgrover1** [comment]
<p>I didn't check this cell after the linter went through... it supposed to be a subsection title with "Calculate the Annual Average <strong>Incorrectly</strong>"</p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/138/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mgrover1** [comment]
<p>Good point- I'll pass in explicit x/y axes</p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/138/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mgrover1** [comment]
<p>I can just move time to x-axis - that way the member_id shows up well, and it's consistent with the other plot</p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/138/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mgrover1** [comment]
<p>Units are in degC </p><p> </p><p><code></code><code></p><p>units :</p><p>degC</p><p></code><code></code></p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/138/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by andersy005** [comment]
<p>I could be missing something here but I think the unit attribute doesn't agree with the actual data..... Can the ocean have potential temperature of 270 deg C? </p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/138/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dcherian** [comment]
yeah.. that's Kelvin.

**Comment by mgrover1** [comment]
<p>It agrees - I think Gary ran some sort of CMOR-ization with the data... I plotted up the initial dataset field TEMP before the processing, and it is in units degC. </p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/138/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mgrover1** [comment]
> I could be missing something here but I think the unit attribute doesn't agree with the actual data..... Can the ocean have potential temperature of 270 deg C?
> 
> [View entire conversation](https://app.reviewnb.com/NCAR/esds/pull/138/discussion/) on ReviewNB

Here is an example plot of the original data - the units are in `degC` - I think there was some sort of CMOR-ization that occurred.
Screen Shot 2021-11-19 at 1 46 07 PM

**Comment by mgrover1** [comment]
<p>Good catch! Thanks!</p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/138/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mgrover1** [comment]
<p>Yeah.... that is why the values were so large. thanks!!</p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/138/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mgrover1** [comment]
<p>Changing the first value to an average instead of a sum fixed it!</p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/138/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mgrover1** [comment]
Thanks @mnlevy1981 for finding where I was taking the resampled sum for the incorrect method which led it to be **very** incorrect... I fixed that, and changed the colorbars accordingly.

**Review by andersy005 — APPROVED** [review]
Looks great 👍🏽 !

**Pull request merged**
