### PR TITLE
Change Office Hours instructions and links to use Acuity Scheduling

### PR DESCRIPTION
**Pull request by jukent**
Adds new Acuity scheduling site embed on the ESDS site for office hours. I still want to see if we can leverage Duo to only allow NCAR employees to view the site (our general scheduling site is set to private, but the direct link to the office hours scheduling is still viewable)

### CODE REVIEW

**Comment by clyne** [comment]
Thanks for doing this @jukent. What is the easiest way to preview the rendered changes?  Thanks!

**Comment by jukent** [comment]
@clyne you're right we're missing a contributor's guide for this site. I checkout out the PR locally with GitHub desktop, opened it in VS Code, and right clicked "open in browser" to see the new `office-hours` page. But I'd like to be able to see the changes the top navbar.

**Comment by jukent** [comment]
It builds correctly now! But there are too many options in the top nav bar and they don't render well.

Screen Shot 2022-08-09 at 2 35 06 PM

**Comment by jukent** [comment]
Screen Shot 2022-08-09 at 4 24 12 PM

I've fixed the navbar. I think this is ready to go!

**Comment by jukent** [comment]
Added steps for previewing site in https://github.com/NCAR/esds/pull/193

**Review by clyne — APPROVED** [review]
Looks great, @jukent. i'm excited to hear about how this works out.

**Comment by jukent** [comment]
@clyne Do you know anything about embedding a site behind a Duo push? I asked UCAR security. Their security assessment seemed to only require that we don't post PII, not that we use the push - but I still think it would be nice for keeping non-UCAR people from making appointments.

**Comment by clyne** [comment]
Sorry, I do not.

**Pull request merged**
