### PR TITLE
Reorganize posts directory: Use subdirectories

### PR DESCRIPTION
**Pull request by andersy005**
@mgrover1, let me know if this new structure is good enough and I will fix image paths in individual posts...

### CODE REVIEW

**Comment by mgrover1** [comment]
This structure looks great - I think this will help!!

**Comment by andersy005** [comment]
Great... I'm going to inspect the individual posts to make sure all image paths are up-to-date...

**Comment by andersy005** [comment]
@mgrover1, I fixed the image paths... Please take a look (at your earliest convenience) to confirm that everything is working as expected.

**Review by mgrover1 — APPROVED** [review]
Thanks for taking care of this - I like this new structure.

**Pull request merged**
