### PR TITLE
Add CAM-SE analysis blogpost

### PR DESCRIPTION
**Pull request by katiedagon**

### CODE REVIEW

**Review by kafitzgerald — COMMENTED** [review]
Great idea for a notebook blogpost!  

I added a few comments/suggestions via nbreview (mostly just to add a bit of context and maybe a quick summary if that would easy enough to do).  Getting this published is probably of greater value than fine tuning things though so take them or leave them.

**Comment by erogluorhan** [comment]
@philipc2 this may be of interest to you. See the [spectral element NB](https://app.reviewnb.com/NCAR/esds/pull/243/) and section 1. Regrid CAM-SE output using map file for the Uxarray mention. I didn't try this NB's files out with UXarray, but if they are already supported, it would be great to mention your recent viz helpers somewhere in this NB (in addition to mentioning our [issue](https://github.com/UXARRAY/uxarray/issues/183#issuecomment-1343388433)).

**Comment by TeaganKing** [comment]
<p>I would second this suggestion! Maybe mentioning ESMF_RegridWeightGen as a tool to generate mapfiles would be useful.</p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/243/discussion/#comment-1696460084'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by TeaganKing — COMMENTED** [review]
I added a few more comments in ReviewNB, as well. This seems well-structured and very useful!

**Comment by katiedagon** [comment]
<p>Thanks Teagan! The blog post has an author tag, which you specify in the notebook metadata, so I was able to add my name there. It should show up on the website that way. Here I wanted to acknowledge you and others who contributed to the code/ideas in the notebook. I could also just add you all as authors in the notebook metadata -- what do you think?</p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/243/discussion/#comment-1696525171'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by katiedagon** [comment]
<p>Great idea! I've never actually generated a map file - Teagan do you know if there is a good link to use to direct others to the appropriate ESMF code/tool?</p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/243/discussion/#comment-1696460084'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by katiedagon** [comment]
<p>Fixed!</p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/243/discussion/#comment-1696460119'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by katiedagon** [comment]
<p>Great idea - done.</p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/243/discussion/#comment-1696525181'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by katiedagon** [comment]
<p>Good suggestion - short summary added to the end. I don't really have a good sense of which is "best", but hopefully as others utilize the code we can have more discussions about the various approaches.</p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/243/discussion/#comment-1696460162'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by kafitzgerald** [comment]
<p>That sounds perfect!</p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/243/discussion/#comment-1696460162'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by TeaganKing** [comment]
<p>Perfect, I'm glad that will be clear from the metadata! That makes sense to keep acknowledgements within the notebook.</p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/243/discussion/#comment-1696525171'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by TeaganKing** [comment]
<p>Looks great! The summary you added is really helpful, too.</p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/243/discussion/#comment-1696525181'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by TeaganKing** [comment]
<p>Here's the <a href="https://earthsystemmodeling.org/docs/release/ESMF_8_0_1/ESMF_refdoc/node3.html#SECTION03020000000000000000" target="_blank">ESMF tool documentation</a> (this is the one I'm more familiar with, although there is also an <a href="https://earthsystemmodeling.org/esmpy_doc/release/latest/html/examples.html#regridding" target="_blank">ESMPy version tutorial</a> which may be useful).</p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/243/discussion/#comment-1696460084'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dcherian** [comment]
> I could also just add you all as authors in the notebook metadata 

:+1: . I also like adding the ["Co-authored-by" line](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) to the commit message.

**Comment by katiedagon** [comment]
<p>@dcherian chimed in with a thumbs up for adding authors to the notebook metadata so I think I will do that instead, it seems cleaner. This is a good discussion though on how we properly credit blog post contributors. Co-authorship on commits is good to know about too.</p>

---

 <a href='https://app.reviewnb.com/NCAR/esds/pull/243/discussion/#comment-1696525171'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by philipc2** [comment]
> > @philipc2 this may be of interest to you. See the [spectral element NB](https://app.reviewnb.com/NCAR/esds/pull/243/) and section (1) "Regrid CAM-SE output using map file" for the Uxarray mention. I didn't try this NB's files out with UXarray, but if they are already supported, it would be great to mention your recent viz helpers somewhere in this NB (in addition to mentioning our [UXARRAY/uxarray#183 (comment)](https://github.com/UXARRAY/uxarray/issues/183#issuecomment-1343388433)).
> 
> @erogluorhan @philipc2 let me know if there is anything you'd like to add to this notebook from the UXarray side. I think we're pretty close to finalizing it.

The notebook looks great!! The only thing possibly worth adding in the UXarray section is a link to our [new usage example notebook](https://uxarray.readthedocs.io/en/latest/examples/005-to-geodataframe-for-holoviz.html), which has a few visualization examples. Other than that I dont have any objections!

**Review by philipc2 — APPROVED** [review]

**Pull request merged**
