### PR TITLE
ESDS Website Updates: communication & relevant projects

### PR DESCRIPTION
**Pull request by TeaganKing**
This PR includes the following changes:

- removed the calendar page
- updated communication methods
- updated relevant projects

Additional contributors: @katiedagon @rmshkv @kafitzgerald @jukent @clyne 

To Do:

- [x] Are there any common questions we aren’t answering on our FAQ page, perhaps from folks running office hours?
- [x] Does joining the Google Group actually send a Zulip invitation to new members? If not, I should clarify these details in `communication.md`. @jukent 
- [x] Is AWSIG moving to monthly meetings? And is there a google meet or zoom link for this? If so, I can make these changes to the "AWSIG / Organization" section of `communication.md`. @clyne @benkirk

### CODE REVIEW

**Comment by kafitzgerald** [comment]
A few more thoughts:

> Are there any common questions we aren’t answering on our FAQ page, perhaps from folks running office hours?
* A couple of things that come to mind are pointers to more getting started level resources and broader scientific python resources (currently we have a bit of a narrow focus in the FAQ section on gridded climate data analysis)
* We could also probably use to update a few resources and/or point to some that may not have existed when these were last updated
* This seems like a reasonable effort itself though.  Maybe we log an issue?  

> Is AWSIG moving to monthly meetings? And is there a google meet or zoom link for this? If so, I can make these changes to the "AWSIG / Organization" section of `communication.md`.
* These happen during the ESDS Forum time slot and use the same link (you can kind of tell from the ESDS Forum sign up sheet, there's an AWSIG label, and we usually mention this in the announcements, but is admittedly confusing).  The cadence is roughly monthly when it works out and we just coordinate w/ the Forum schedule.  That all said, I agree it'd be great to have a little more clarity surrounding this. I was also confused by the way we describe it in the communication page.  Maybe we frame it as part of the ESDS Forum or have a higher level Events/Meetings category?  I think brief "what it is" and "who is it for" needs to come sooner in the description as well (this could be helpful for a few of the communication page items).

**Comment by jukent** [comment]
Yeah I'm not sure if that's true about the automatic invitation. I don't have admin rights in this group to be able to check.

**Comment by TeaganKing** [comment]
Thanks for these suggestions, @jukent and @kafitzgerald .

I added some broader organization to the communication page, tried to clarify the AWSIG meetings as part of ESDS forum, added a table of contents to the FAQ page for clarity, and added an issue regarding those details on the FAQ page (#257).

I did clarify how to separately add yourself to either via the Zulip invite link or the email invite link. The thought was that people have the ability to add themselves to Zulip and/or email, and if someone gets an automatic Zulip invite, that's nifty (but not absolutely necessary to be functional).

**Review by clyne — APPROVED** [review]
Thanks for these much needed updates, @TeaganKing !

**Pull request merged**
