### PR TITLE
Merge Xdev's blog with ESDS' blog

### PR DESCRIPTION
**Pull request by andersy005**
First stab at merging xdev and esds blogs. ~~This is still work in progress...~~

### CODE REVIEW

**Comment by mgrover1** [comment]
@andersy005 this looks great!

**Comment by andersy005** [comment]
@NCAR/xdev, this is ready for review. For everything to work properly, once this PR is merged, the gh-pages on https://github.com/NCAR/esds needs to be served from the `redirect` branch: https://github.com/NCAR/xdev/tree/redirect

**Review by mgrover1 — APPROVED** [review]
This looks great @andersy005 - thank you for putting this together.

**Comment by andersy005** [comment]
> This looks great @andersy005 - thank you for putting this together.

Of course! Thank you, too

**Pull request merged**
