### PR TITLE
Add blog post about using kerchunk with CESM2 data

### PR DESCRIPTION
**Pull request by mgrover1**

### CODE REVIEW

**Comment by dcherian** [comment]
ahahah I merged #230 and didn't see this one.

@mgrover1 I knew I had seen your experiment with it but couldn't find it online!

**Comment by mgrover1** [comment]
No worries @dcherian :)

**Comment by dcherian** [comment]
Are you interested in updating it or shall we jsut merge as-is?

**Comment by mgrover1** [comment]
I can go ahead and execute it to make sure everything still works first - there have been some kerchunk API changes

**Comment by mgrover1** [comment]
@dcherian - the only update needed here was the imports. Would you be able to execute on Casper? I no longer have access, and was not able to run it on my local machine since it took a fair amount of computational resources.

**Comment by dcherian** [comment]
Do you remember if there was a motivating use-case here?

I've found it funny to be accessing AWS catalogs from casper, but I guess if you didn't have access to JupyterHub in the cloud instance.

**Comment by clyne** [comment]
@dcherian, @mgrover1,

My timing is bad (I was off the grid), but is it worth referencing the new [Pythia Kerchunk Cookbook](https://projectpythia.org/kerchunk-cookbook/README.html) here?

**Comment by dcherian** [comment]
Sounds good. I'll add that

**Comment by mgrover1** [comment]
Thanks for all your help with this @dcherian

**Comment by dcherian** [comment]
Thanks for engaging when you don't need to!

**Pull request merged**
