### PR TITLE
add cesm2-le post

### PR DESCRIPTION
**Pull request by mgrover1**

### CODE REVIEW

**Comment by andersy005** [comment]
You could replace this loop with the wildcard search

```python
for var in cat.search(component='atm').df.long_name.unique():
    
    if 'temperature' in var.lower():
        print(var)

```


```python
In [7]: cat.search(component='atm', long_name='temperature*').df.long_name.unique()
Out[7]: 
array(['sea surface temperature',
       'Minimum reference height temperature over output period',
       'Reference height temperature', 'Total temperature tendency',
       'Minimum surface temperature over output period',
       'Maximum reference height temperature over output period',
       'Maximum surface temperature over output period',
       'Surface temperature (radiative)',
       'Lowest model level temperature'], dtype=object)
```

**Comment by mgrover1** [comment]
> You could replace this loop with the wildcard search
> 
> ```python
> for var in cat.search(component='atm').df.long_name.unique():
>     
>     if 'temperature' in var.lower():
>         print(var)
> ```
> 
> ```python
> In [7]: cat.search(component='atm', long_name='temperature*').df.long_name.unique()
> Out[7]: 
> array(['sea surface temperature',
>        'Minimum reference height temperature over output period',
>        'Reference height temperature', 'Total temperature tendency',
>        'Minimum surface temperature over output period',
>        'Maximum reference height temperature over output period',
>        'Maximum surface temperature over output period',
>        'Surface temperature (radiative)',
>        'Lowest model level temperature'], dtype=object)
> ```

is there a way to search for 'temperature' or 'Temperature' since some long names include the capital T version?

**Comment by mgrover1** [comment]
> > You could replace this loop with the wildcard search
> > ```python
> > for var in cat.search(component='atm').df.long_name.unique():
> >     
> >     if 'temperature' in var.lower():
> >         print(var)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```python
> > In [7]: cat.search(component='atm', long_name='temperature*').df.long_name.unique()
> > Out[7]: 
> > array(['sea surface temperature',
> >        'Minimum reference height temperature over output period',
> >        'Reference height temperature', 'Total temperature tendency',
> >        'Minimum surface temperature over output period',
> >        'Maximum reference height temperature over output period',
> >        'Maximum surface temperature over output period',
> >        'Surface temperature (radiative)',
> >        'Lowest model level temperature'], dtype=object)
> > ```
> 
> is there a way to search for 'temperature' or 'Temperature' since some long names include the capital T version?

😁 got it 
```python
cat.search(component='atm', long_name=['temperature*', 'Temperature*'])
```

**Comment by andersy005** [comment]
> cat.search(component='atm', long_name=['temperature*', 'Temperature*'])

👍🏽 

If you want to go down the regular expression rabbit hole, here's a version with Case insensitive regular expression

```python
In [10]: cat.search(component='atm', long_name='(?i)temperature*').df.long_name.unique()
Out[10]: 
array(['sea surface temperature',
       'Minimum reference height temperature over output period',
       'Tropopause Temperature', 'Reference height temperature',
       'Total temperature tendency',
       'Minimum surface temperature over output period',
       'Temperature tendency',
       'Maximum reference height temperature over output period',
       'Temperature', 'Maximum surface temperature over output period',
       'Potential Temperature', 'Temperature Variance',
       'Surface temperature (radiative)',
       'Temperature at  700 mbar pressure surface',
       'Temperature at 700 mbar pressure surface',
       'Temperature at 200 mbar pressure surface',
       'Temperature at  200 mbar pressure surface',
       'Temperature at 1000 mbar pressure surface',
       'Temperature at  100 mbar pressure surface',
       'Temperature at   50 mbar pressure surface',
       'Temperature at 500 mbar pressure surface',
       'Temperature at  500 mbar pressure surface',
       'Lowest model level temperature',
       'Temperature at   10 mbar pressure surface',
       'Temperature at 850 mbar pressure surface',
       'Temperature at  850 mbar pressure surface'], dtype=object)
```

**Comment by andersy005** [comment]
@mgrover1, Could you add a legend to the plot (if it's not too much work of course :))?

**Review by andersy005 — APPROVED** [review]

**Comment by dcherian** [comment]
``` python

# Loop through and plot each member_id
for member_id in da.member_id.values:
    da.sel(member_id=member_id).plot(ax=ax, label=member_id)

```

Good place to highlight the `hue` kwarg!
``` python
da.sel(member_id=member_id).plot(ax=ax, hue="member_id")
```

**Comment by mgrover1** [comment]
@de

> ```python
> # Loop through and plot each member_id
> for member_id in da.member_id.values:
>     da.sel(member_id=member_id).plot(ax=ax, label=member_id)
> ```
> 
> Good place to highlight the `hue` kwarg!
> 
> ```python
> da.sel(member_id=member_id).plot(ax=ax, hue="member_id")
> ```

what exactly does `hue` do here?

**Comment by dcherian** [comment]
Oops delete the sel statement

**Comment by mgrover1** [comment]
neat! I didn't know that was an option there... currently editing the notebook!

**Comment by mgrover1** [comment]
@dcherian is there an easy way to handle the legend labels for each of these too?

**Comment by dcherian** [comment]
I thought it did it automatically?

**Comment by mgrover1** [comment]
Nope... it returns `No handles with labels found to put in legend.`

**Comment by mgrover1** [comment]
Using version 0.17.0

**Comment by andersy005** [comment]
> neat! I didn't know that was an option there... currently editing the notebook!

Could you include these changes too?

Screen Shot 2021-08-06 at 4 36 54 PM
Screen Shot 2021-08-06 at 4 36 48 PM

**Comment by mgrover1** [comment]
There are some annoying conflicts...

**Comment by mgrover1** [comment]
See #90

**Pull request merged**
